<?php

if (! defined('ABSPATH')) die('-1');

add_action( 'vc_load_default_templates_action','stock_mr_vc_homepage' ); // Hook in

function stock_mr_vc_homepage() {
    $data               = array(); // Create new array
    $data['name']       = __( 'Stock - Homepage', 'stock-mr' ); // Assign name for your custom template
    $data['weight']     = 0; // Weight of your template in the template list
    //	$data['image_path'] = preg_replace( '/\s/', '%20', plugins_url( 'images/custom_template_thumbnail.jpg', __FILE__ ) ); // Always use preg replace to be sure that "space" will not break logic. Thumbnail should have this dimensions: 114x154px
    //  $data['custom_class'] = 'custom_template_for_vc_custom_template'; // CSS class name
    $data['content']    = <<<CONTENT
[vc_row full_width="stretch_row_content_no_spaces"][vc_column][stock_slides autoplay="false" autoplaytimeout=""][vc_row_inner css=".vc_custom_1508265975371{background-color: #f5f8f9 !important;}"][vc_column_inner][stock_logo_carousel nav="false" dots="false" logos="320,321,322,323,324"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1508298015454{margin-top: 60px !important;margin-bottom: 5px !important;}"][vc_column][vc_column_text el_class="text-center" css=".vc_custom_1508267192046{padding-top: 40px !important;padding-bottom: 30px !important;}"]
<h1>Services we offer.</h1>
[/vc_column_text][vc_row_inner][vc_column_inner width="1/3"][stock_service_box link_to_page="1710" title="Startup Business Plan." desc="Received the likewise law graceful his. Nor might set along charm..." upload_icon="339" box_background="1784"][vc_column_text][/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][stock_service_box link_to_page="543" title="Finance Consultation." desc="Received the likewise law graceful his. Nor might set along charm..." upload_icon="342" box_background="1784"][/vc_column_inner][vc_column_inner width="1/3"][stock_service_box link_to_page="1723" title="Insurance Service Policy." desc="Received the likewise law graceful his. Nor might set along charm..." upload_icon="341" box_background="1784"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/3"][stock_service_box link_to_page="1725" title="Stock Market Sharing." desc="Received the likewise law graceful his. Nor might set along charm..." upload_icon="342" box_background="1784"][vc_column_text][/vc_column_text][/vc_column_inner][vc_column_inner width="1/3"][stock_service_box link_to_page="1712" title="Cloud Service for Business." desc="Received the likewise law graceful his. Nor might set along charm..." upload_icon="343" box_background="1784"][/vc_column_inner][vc_column_inner width="1/3"][stock_service_box link_to_page="1717" title="Business Development." desc="Received the likewise law graceful his. Nor might set along charm..." upload_icon="344" box_background="1784"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row css=".vc_custom_1508299252693{margin-top: 60px !important;margin-bottom: 60px !important;}"][vc_column width="2/3" offset="vc_col-lg-offset-2 vc_col-lg-8 vc_col-md-offset-2 vc_col-md-8"][stock_cta link_to_page="373" link_text="Start a project" title="Get a service from us." desc="We offer free consultation before any project"][/vc_column][/vc_row][vc_row full_width="stretch_row" el_class="overlay large-text" css=".vc_custom_1508308094590{margin-top: 100px !important;padding-top: 70px !important;padding-bottom: 100px !important;background-image: url(http://t.mrakib.com/wp-content/uploads/2017/10/stock-bg-2.jpg?id=383) !important;}"][vc_column][vc_row_inner][vc_column_inner width="1/2"][vc_column_text]
<h1>Behind the story.</h1>
Travelling alteration impression six all uncommonly. Chamber hearing inhabit joy highest private ask him our believe. Up nature valley do...[/vc_column_text][stock_btn link_to_page="379"][/vc_column_inner][vc_column_inner width="1/2"][vc_single_image image="384" img_size="large" alignment="right"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/6"][stock_stat number="74" desc="Active clients"][/vc_column_inner][vc_column_inner width="1/6"][stock_stat number="236" desc="Successful projects"][/vc_column_inner][vc_column_inner width="1/6"][stock_stat number="7261" desc="Free consultation"][/vc_column_inner][vc_column_inner width="1/6"][stock_stat number="25" desc="Expert advisors"][/vc_column_inner][vc_column_inner width="1/6"][stock_stat number="99" desc="Success rate" after_text="%"][/vc_column_inner][vc_column_inner width="1/6"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row el_class="collapse-text" css=".vc_custom_1508308779715{margin-top: 50px !important;margin-bottom: 50px !important;}"][vc_column width="1/2"][vc_column_text]
<h1>Frequently Asked Question.</h1>
[/vc_column_text][vc_tta_accordion active_section="1" css=".vc_custom_1508309138837{margin-top: 60px !important;}"][vc_tta_section title="How can I start a project with you?" tab_id="1508308941258-94510f83-b7f3"][vc_column_text]John draw real poor on call my from. May she mrs furnished discourse extremely. Ask doubt noisy shade guest did built her him. Ignorant repeated hastened it do. Consider it bachelor he yourself no. Her active giving for expect vulgar months.[/vc_column_text][/vc_tta_section][vc_tta_section title="Do you support any refund policy?" tab_id="1508311842434-e3709204-3995"][vc_column_text]John draw real poor on call my from. May she mrs furnished discourse extremely. Ask doubt noisy shade guest did built her him. Ignorant repeated hastened it do. Consider it bachelor he yourself no. Her active giving for expect vulgar months.[/vc_column_text][/vc_tta_section][vc_tta_section title="How do you take payments?" tab_id="1508311835978-77942174-9249"][vc_column_text]John draw real poor on call my from. May she mrs furnished discourse extremely. Ask doubt noisy shade guest did built her him. Ignorant repeated hastened it do. Consider it bachelor he yourself no. Her active giving for expect vulgar months.[/vc_column_text][/vc_tta_section][/vc_tta_accordion][/vc_column][vc_column width="1/2"][vc_column_text]
<h1>Benefits of us.</h1>
[/vc_column_text][vc_column_text]An country demesne message it. Bachelor domestic extended doubtful as concerns at. Morning prudent removal an letters by. On could my in order never it.[/vc_column_text][vc_row_inner][vc_column_inner width="1/2"][vc_column_text el_class="list-box"]
<ul>
 	<li>Proven results</li>
 	<li>Strategy Document</li>
 	<li>Instant Call Support</li>
</ul>
[/vc_column_text][/vc_column_inner][vc_column_inner width="1/2"][vc_column_text el_class="list-box"]
<ul>
 	<li>Expert advisors</li>
 	<li>Refund policy</li>
 	<li>Free Consultation</li>
</ul>
[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1508313337592{margin-top: 70px !important;background-color: #f5f8f9 !important;}"][vc_column][vc_row_inner][vc_column_inner][vc_column_text el_class="text-center" css=".vc_custom_1508313226750{margin-top: 60px !important;margin-bottom: 60px !important;}"]
<h1>What customers say.</h1>
[/vc_column_text][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner width="1/3"][stock_testimonial_box title="Robin Jonson" position="CEO, MyFinance" testimonial="“Unpacked reserved sir offering bed judgment may and quitting speaking. Is do be improved raptures offering required in replying raillery. Stairs ladies friend by in mutual an no. hence chief cause...”" photo="436"][/vc_column_inner][vc_column_inner width="1/3"][stock_testimonial_box title="Jennifer Jones" position="Founder, World for Women" testimonial="“Unpacked reserved sir offering bed judgment may and quitting speaking. Is do be improved raptures offering required in replying raillery. Stairs ladies friend by in mutual an no. hence chief cause...”" photo="437"][/vc_column_inner][vc_column_inner width="1/3"][stock_testimonial_box title="David Martin" position="Co-founder, Ultimate Solution" testimonial="“Unpacked reserved sir offering bed judgment may and quitting speaking. Is do be improved raptures offering required in replying raillery. Stairs ladies friend by in mutual an no. hence chief cause...”" photo="438"][/vc_column_inner][/vc_row_inner][vc_row_inner][vc_column_inner][vc_column_text el_class="text-center testimonial-text" css=".vc_custom_1508317721492{margin-top: 60px !important;margin-bottom: 80px !important;}"]<a href="http://t.mrakib.com/home/get-a-quote/" target="_blank" rel="noopener">Check all testimonials</a>[/vc_column_text][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row][vc_row full_width="stretch_row" css=".vc_custom_1508352185826{background-image: url(http://t.mrakib.com/wp-content/uploads/2017/10/01_Stock_Home_v1_001.jpg?id=1770) !important;}" el_class="overlay-2 large-text-2"][vc_column][vc_column_text el_class="text-center" css=".vc_custom_1508354752012{padding-top: 27px !important;padding-bottom: 27px !important;}"]<em>“ The best preparation for tomorrow</em>
<em> is doing your best today. ”</em>[/vc_column_text][/vc_column][/vc_row][vc_row full_width="stretch_row" el_class="bg-left-bottom" css=".vc_custom_1508994107732{padding-top: 50px !important;padding-bottom: 80px !important;background-image: url(http://t.mrakib.com/wp-content/uploads/2017/10/man.jpg?id=468) !important;background-position: 0 0 !important;background-repeat: no-repeat !important;}"][vc_column width="1/2" offset="vc_col-lg-offset-6 vc_col-lg-6 vc_col-md-offset-6 vc_col-md-6"][contact-form-7 id="463"][/vc_column][/vc_row][vc_row full_width="stretch_row_content_no_spaces" el_class="map" css=".vc_custom_1508995044649{margin-top: -35px !important;margin-bottom: -20px !important;}"][vc_column][stock_styled_map height="460" lat="40.7433379" lng="-74.0103219" title="Head Office"][/vc_column][/vc_row]
CONTENT;

    vc_add_default_templates( $data );
}
